version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: siggia-procaci-nest
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000